#!/usr/bin/env bash

[[ -n "${DEBUG:-}" ]] && set -x

set -Eeuo pipefail

VERSION="0.0.1a"

usage(){
    echo "USAGE: $0 [-<h|-help>] [--post <POST>] [-<p|-persona> <NAME[+NAME]...>] [-<m|-model> <MODEL>] [--python] [--markdown] -- <prompt>"
}

if [[ $# -eq 0 ]];then
    usage
    exit 1
fi

post(){
    bash "./post/${POST:-default}"
}

while [[ $# -gt 0 ]];do
    case $1 in
        "--help"|"-h")
            usage
            exit 1
            ;;
        "--")
            shift
            break
            ;;
        "--markdown")
            shift
            POST=markdown
            PERSONA=markdown
            ;;
        "--post")
            shift
            POST="$1"
            shift
            ;;
        "--persona"|"-p")
            shift
            export PERSONA=$1
            shift
            ;;
        "--python")
            shift
            POST=python
            export PERSONA=python+concise+runnable
            ;;
        "--model"|"-m")
            shift
            export MODEL="$1"
            shift
            ;;
        "--temperature"|"-t")
            shift
            export TEMPERATURE=$1
            shift
            ;;
        *)
            echo "Unknown arg: $1"
            exit 1
            ;;
    esac
done

read_stdin(){
    echo "reading from stdin..." >&2
    local _buf=""
    while IFS='' read _line; do
        echo "$_line"
    done
}

./endpoints.sh "${@:-$(read_stdin)}" | post
