#!/usr/bin/env bash

[[ -n "${DEBUG:-}" ]] && set -x

set -Eeuo pipefail

usage(){
    echo "USAGE: $0 [-<h|-help>] [-<p|-persona> <NAME[+NAME]...>] [-<m|-model> <MODEL>] [--python] [-<c|-continue>] -- <prompt>"
}

if [[ $# -eq 0 ]];then
    usage
    exit 1
fi

post(){
    case ${POST:-} in
        python)
            python -c -
            ;;
        *)
            cat
            ;;
    esac
}

CONTINUE=0

while [[ $# -gt 0 ]];do
    case $1 in
        "--help"|"-h")
            usage
            exit 1
            ;;
        "--")
            shift
            break
            ;;
        "--persona"|"-p")
            shift
            export PERSONA=$1
            shift
            ;;
        "--python")
            shift
            POST=python
            export PERSONA=python+concise+runnable
            ;;
        "--continue"|"-c")
            shift
            export CONTINUE=1
            shift
            ;;
        "--model"|"-m")
            shift
            export MODEL="$1"
            shift
            ;;
        "--temperature"|"-t")
            shift
            export TEMPERATURE=$1
            shift
            ;;
        *)
            echo "Unknown arg: $1"
            exit 1
            ;;
    esac
done

msg="$@"

./endpoints.sh "$msg" | post
